server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: STUDENT-SERVICE
                fallbackuri: forward:/studentServiceFallBack
            
    
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack
        
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
           - Path=/auth/**

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

